base_url = "https://scatena.co"
title = "Jason Scatena"
description = "Jason Scatena blog and personal projects"
author = "Jason Scatena"
theme = "tabi"
generate_feeds = true
compile_sass = true
minify_html = true
build_search_index = true
default_language = "en"

taxonomies = [{name = "tags", feed = true}]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
bottom_footnotes = true
smart_punctuation = true

[markdown.highlighting]
theme = "catppuccin-frappe"
style = "class"

[extra]
theme_switcher = true
default_theme = ""
skin = "teal"
show_reading_time = true
show_date = true
show_author = false
copy_button = true
toc = true
enable_csp = false
enable_subset = false
iine = false

menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    { name = "about", url = "about", trailing_slash = true },
]

feed_icon = true
full_content_in_feed = true

email = "jason@scatena.co"
encode_plaintext_email = true

socials = [
    { name = "github", url = "https://github.com/jscatena88/", icon = "github" },
]

footer_menu = [
    {url = "about", name = "about", trailing_slash = true},
    {url = "sitemap.xml", name = "sitemap", trailing_slash = false},
]
